FROM golang:1.21-alpine

# Install packages for installing Helm and Helm unittest plugin
RUN apk add --no-cache bash bind-tools coreutils curl git ncurses openssl

# Install helm
RUN curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

# Install helm unittest plugin
RUN mv /etc/os-release /etc/os-release.bak && \
    touch /etc/os-release && \
    helm plugin install https://github.com/helm-unittest/helm-unittest && \
    mv /etc/os-release.bak /etc/os-release
