{{- if not (isAbs .Values.provider.socketDir) -}}
{{- fail "value for .Values.provider.socketDir must be absolute directory path" -}}
{{- end -}}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.daemonSet.name }}
  namespace: {{ .Release.Namespace }}
{{- with .Values.labels }}
  labels:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  selector:
    matchLabels:
      name: {{ .Values.daemonSet.name }}
{{- with .Values.labels }}
{{ toYaml . | indent 6 }}
{{- end }}
  template:
    metadata:
      labels:
        name: {{ .Values.daemonSet.name}}
{{- with .Values.labels }}
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.annotations }}
      annotations:
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: conjur-provider
        image: {{ .Values.daemonSet.image.repo }}:{{ .Values.daemonSet.image.tag }}
        imagePullPolicy: {{ .Values.daemonSet.image.pullPolicy }}
        args:
          - -socketPath={{ .Values.provider.socketDir }}/{{ .Values.provider.name }}.sock
          - -healthPort={{ .Values.provider.healthPort }}
        ports:
        - containerPort: {{ .Values.provider.healthPort }}
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 50m
            memory: 100Mi
        volumeMounts:
        - name: provider-volume
          mountPath: {{ .Values.provider.socketDir }}
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.provider.healthPort }}
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.provider.healthPort }}
          initialDelaySeconds: 30
          periodSeconds: 30
{{- if not (empty .Values.securityContext) }}
        securityContext:
{{- with .Values.securityContext }}
{{ toYaml . | indent 10 }}
{{- end }}
{{- end }}
      volumes:
      - name: provider-volume
        hostPath:
          path: {{ .Values.provider.socketDir }}
